# Generated by Django 5.1 on 2024-08-20 20:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppShinyLove", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
